import './globals.css'
import { Roboto_Flex as Display} from 'next/font/google'

const display = Display({
  subsets: ['latin'],
  variable: '--font-display',
  axes: ['GRAD', 'slnt', 'XTRA', 'YOPQ', 'YTLC', 'YTUC', 'YTAS', 'YTDE', 'YTFI', 'opsz']
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${display.variable} font-sans`}>
      <body>{children}</body>
    </html>
  )
}
