import './globals.css'
import { Teko as Display} from 'next/font/google'

const display = Display({
  subsets: ['latin'],
  weight: "600",
  variable: '--font-display',
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${display.variable} font-sans`}>
      <body>{children}</body>
    </html>
  )
}
